name: Android APK

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Flutter pub get
        run: flutter pub get

      - name: Enable linux and android (no-op on CI)
        run: |
          flutter config --no-analytics || true
          flutter doctor -v

      # 🩹 Fix flutter_native_timezone namespace error for AGP 8+
      - name: Patch flutter_native_timezone namespace
        run: |
          set -e
          PLUGIN_DIR=$(find $HOME/.pub-cache -type d -path "*/flutter_native_timezone-*/android" | head -n 1)
          if [ -n "$PLUGIN_DIR" ]; then
            echo "⚙️ Patching flutter_native_timezone namespace in: $PLUGIN_DIR/build.gradle"
            echo -e "\nandroid {\n    namespace 'com.crazecoder.flutter_native_timezone'\n}" >> "$PLUGIN_DIR/build.gradle"
          else
            echo "⚠️ flutter_native_timezone plugin not found; skipping patch."
          fi

      - name: Build APK (debug)
        run: flutter build apk --debug

      - name: Build APK (release unsigned)
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-builds
          path: |
            build/app/outputs/flutter-apk/app-debug.apk
            build/app/outputs/flutter-apk/app-release.apk
