name: Android APK

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Ensure Gradle can find Flutter SDK and Android SDK even without local.properties
      - name: Prepare Android local.properties
        run: |
          set -e
          mkdir -p android
          FLUTTER_SDK_PATH="${FLUTTER_HOME:-$FLUTTER_ROOT}"
          if [ -n "$FLUTTER_SDK_PATH" ]; then
            echo "flutter.sdk=$FLUTTER_SDK_PATH" > android/local.properties
          fi
          if [ -n "${ANDROID_SDK_ROOT:-}" ]; then
            echo "sdk.dir=$ANDROID_SDK_ROOT" >> android/local.properties
          elif [ -n "${ANDROID_HOME:-}" ]; then
            echo "sdk.dir=$ANDROID_HOME" >> android/local.properties
          fi
          echo "Created android/local.properties:" && cat android/local.properties

      - name: Flutter pub get
        run: flutter pub get

      - name: Enable linux and android (no-op on CI)
        run: |
          flutter config --no-analytics || true
          flutter doctor -v

      # Remove fragile plugin patch; use plugin versions that work with AGP 8+
      # If plugin issues arise, manage via pubspec versions rather than mutating cache

      - name: Build APK (debug)
        run: flutter build apk --debug

      - name: Build APK (release unsigned)
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-builds
          path: |
            build/app/outputs/flutter-apk/app-debug.apk
            build/app/outputs/flutter-apk/app-release.apk
